### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gahujipo** [ChriD/node-raumserver#36] opened 2017-07-19 19:14 UTC
Every command (except for Get Zone Config) fails with the following error: 
`{requestUrl :  "/raumserver/controller/createZone?id=871ab9db-6305-4cf6-8633-6d7405faadd5&_=1500491016990",
action :  "createZone",
error :  true,
msg :  "Action was rejected",
data : {errorMessage :  "TypeError: Cannot read property 'length' of undefined",
errorData :  null
}
}`

OS: Windows with current release of node.js

- zip downloaded from github, 
- npm install issued. 
- IP of Raumfeld standalone speaker pasted to config/default.json
- Port changed to 8081 (because 8080 on that machine is already in use= 
- node raumserver.js

Danke! :)

**Comment by ChriD** [comment] 2017-07-20 12:11
I will check this. It may take a while because i am on vacation

**Comment by Todelec** [comment] 2017-07-20 12:29
I thought port 8080 is fixed at the moment?
I am using raumserver with openhab 2 on rpi and had to change port of openhab (default 8080) to get it work together

**Comment by ChriD** [comment] 2017-07-20 12:59
@Todelec 
Since version 0.0.8 raumserver has a config file where you can change the port which is beeing used.
https://github.com/ChriD/node-raumserver/releases/tag/0.0.8

**Comment by gahujipo** [comment] 2017-07-20 17:38
@ChriD thank you in the meantime. Have a nice vacation!

**Comment by gahujipo** [comment] 2017-07-20 17:40
@Todelec the get Zone Config command works even with another port than 8080, so I think the port is not the problem. Maybe there is an issue in my situation because the speaker is standalone and there aren't more than one zones.

**Comment by ChriD** [comment] 2017-07-24 21:43
@gahujipo The 'getZoneConfig' request only works on the port you entered in the configuration file. It's not possible that it works on several ports except you have started more than one instances of the node-raumserver.

And i can't reproduce your problem :( 
I will check if i can add the stack trace info for exceptions into the kernel

**Comment by lufiacs** [comment] 2017-07-25 06:13
> The 'getZoneConfig' request only works on the port you entered in the configuration file. It's not possible that it works on several ports except you have started more than one instances of the node-raumserver.

That is correct. Of course the command only works with the port, node-raumserver is started with. 

I don't understand your last two sentences. Do you need kind of a log?

**Comment by gahujipo** [comment] 2017-07-25 06:14
> The 'getZoneConfig' request only works on the port you entered in the configuration file. It's not possible that it works on several ports except you have started more than one instances of the node-raumserver.

That is correct. Of course the command only works with the port, node-raumserver is started with.

I don't understand your last two sentences. Do you need kind of a log?

**Comment by ChriD** [comment] 2017-07-25 07:50
Nope. I will add a stack  trace in the kernel to get the source of the problem.

**Comment by gahujipo** [comment] 2017-08-08 17:47
Have you been able to dig into this?

**Comment by ChriD** [comment] 2017-08-09 16:01
Sorry, Not yet!

**Comment by gahujipo** [comment] 2017-09-02 13:50
The response to the "/raumserver/data/getZoneConfig"-command looks like this while my speaker is playing music from Spotify. 

```jQuery
{
  requestUrl :    "/raumserver/data/getZoneConfig?_=1504358833993",
  action :    "getZoneConfig",
  error :   false,
  msg :    "",
  data :  {
    zoneConfig :  {
      $ :  {
        numRooms :    "1",
        spotifyMode :    "singleRoom"
      },
      unassignedRooms :  [{
        room :  [{
          $ :  {
            name :    "Schlafzimmer",
            udn :    "uuid:871ab9db-…",
            powerState :    "ACTIVE"
          },
          renderer :  [{
            $ :  {
              udn :    "uuid:e6d93437-…",
              name :    "Speaker Schlafzimmer",
              spotifyConnect :    "active"
            }
          }]
        }]
      }]
    }
  }
}
```

- The commands
- Get Renderer State  
- Play All  
- Stop All  
- Pause All  
- Next  
- Prev  
- Set Sleep Timer  
- Cancel Sleep Timer 
- Get Sleep Timer State 
- Mute All  
- UnMute All  
- Toggle Mute
create this error: 
```jQuery 
{
  requestUrl :  "/raumserver/controller/pause?_=1504358834017",
  action :  "pause",
  error :  true,
  msg :  "Action was rejected",
  data : {
   errorMessage :  "Error: VirtualMediaRenderer for id '' not found",
   errorData :  null
  }
}
```

do other commands (except get zone config) fail because my single room is "unassigned" and therefore I don't get any room or zone IDs? Does that maybe make the queries fail? How can I "assign" the room? Are there needed more than one speaker on the network?

**Comment by gahujipo** [comment] 2017-09-02 14:06
Oh, I got it working. Spotify has to be in the "Multiroom Mode". Then node-raumserver has to be restarted (maybe because it needs to rediscover the refreshed speaker config). Afterwards all tested commands against node-raumserver seem to work. Amazing! 🎉

**Comment by tomquist** [comment] 2017-10-01 09:49
I get this error as well.
This is the stacktrace:
```
0|raumserv | error: [Request.leaveStandby] Some renderers had exceptions:  TypeError: Cannot read property 'length' of undefined
0|raumserv |     at ZoneManager.getRoomObjectFromMediaRendererUdnOrName (/home/tom/node_modules/node-raumkernel/lib/lib.manager.zoneManager.js:441:92)
0|raumserv |     at ZoneManager.getRoomNameForMediaRendererUDN (/home/tom/node_modules/node-raumkernel/lib/lib.manager.zoneManager.js:371:28)
0|raumserv |     at UPNPMediaRendererRaumfeld.roomName (/home/tom/node_modules/node-raumkernel/lib/lib.device.upnp.mediaRenderer.raumfeld.js:19:49)
0|raumserv |     at DeviceManager.getMediaRenderer (/home/tom/node_modules/node-raumkernel/lib/lib.manager.deviceManager.js:732:72)
0|raumserv |     at DeviceManager.getVirtualMediaRenderer (/home/tom/node_modules/node-raumkernel/lib/lib.manager.deviceManager.js:704:34)
0|raumserv |     at Request_LeaveStandby.getMediaRenderersFromIdAndScope (/home/tom/node_modules/node-raumserver/lib/lib.base.request.js:134:68)
0|raumserv |     at Request_LeaveStandby.run (/home/tom/node_modules/node-raumserver/lib/lib.base.requestMediaRenderer.js:68:39)
0|raumserv |     at Raumserver.handleRequestObject (/home/tom/node_modules/node-raumserver/lib/lib.raumserver.js:143:28)
0|raumserv |     at Raumserver.requestReceived (/home/tom/node_modules/node-raumserver/lib/lib.raumserver.js:106:22)
0|raumserv |     at Server.<anonymous> (/home/tom/node_modules/node-raumserver/lib/lib.raumserver.js:80:26)
0|raumserv |     at emitTwo (events.js:106:13)
0|raumserv |     at Server.emit (events.js:194:7)
0|raumserv |     at parserOnIncoming (_http_server.js:563:12)
0|raumserv |     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

This is my zone config:
```
{
  "action": "getZoneConfig",
  "data": {
    "zoneConfig": {
      "$": {
        "numRooms": "1",
        "spotifyMode": "singleRoom"
      },
      "unassignedRooms": [
        {
          "room": [
            {
              "$": {
                "name": "Buffet",
                "powerState": "ACTIVE",
                "udn": "uuid:75073f6f-b05e-4f7a-abd8-8782ed6be1a8"
              },
              "renderer": [
                {
                  "$": {
                    "name": "Speaker Buffet #2",
                    "udn": "uuid:3ff651bc-b8ee-41fa-83eb-91334c6f192d"
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "error": false,
  "msg": "",
  "requestUrl": "/raumserver/data/getZoneConfig"
}
```

**Comment by gahujipo** [comment] 2017-10-01 11:48
Try to switch Spotify to multiroom mode as described in my previous comment.

**Comment by tomquist** [comment] 2017-10-01 18:34
Yes, that might be a workaround but the problem still persists and should be fixed. The problem even occurs when calling `/raumserver/controller/leaveStandby?id=<someID>` which doesn't have to do anything with my zone configuration or Spotify. Maybe I find the time to give it a try to fix the issue in Raumkernel.

**Comment by ChriD** [comment] 2017-10-02 11:18
The problem seems to be that i assume that there is always a zone. This is indeed not correct.
I 'll merge the fix provided by tomquist!

**Comment by gahujipo** [comment] 2017-10-04 17:54
I added to my config another speaker and would really like to disable the multiroom mode once this is fixed. As this issue is reproducible and @tomquist has already provided a mergeable fix I reopen this issue.

**Comment by tomquist** [comment] 2017-10-04 18:43
My commit didn't completely fix the issue. Didn't had time to look into it again but I will open a pull request once I finished my fix.

**Comment by gahujipo** [comment] 2017-10-19 08:57
@tomquist what behaviour do you get after applying your code in node-raumkernel?

**Comment by ChriD** [comment] 2018-01-12 16:07
i have updated the kernel in some places wheer this problem might occur. It's not on npm yet but i think i will get it up this weekend

**Closed** 2018-01-13 11:37 UTC
Labels: bug, investigation, merge

**Comment by gahujipo** [comment] 2018-01-17 18:10
I do not really need this but just for you info: 

I changed my zone configuration to test this. It now looks like this: 
```JS 
{
	requestUrl: "/raumserver/data/getZoneConfig?_=1516211865682",
	action: "getZoneConfig",
	error: false,
	msg: "",
	data: {
		zoneConfig: {
			$: {
				numRooms: "2",
				spotifyMode: "singleRoom"
			},
			zones: [{
				zone: [{
					$: {
						udn: "uuid:ffffffff-8d8b-fce1-ffff-ffff8d8bfce1"
					},
					room: [{
						$: {
							name: "Badezimmer",
							udn: "uuid:56d49d64-0eaa-4f35-a0b2-4f3f102e550d",
							powerState: "MANUAL_STANDBY"
						},
						renderer: [{
							$: {
								udn: "uuid:645f498e-4840-46b1-9305-a4dc2a62a439",
								name: "Speaker Badezimmer"
							}
						}]
					}]
				}]
			}],
			unassignedRooms: [{
				room: [{
					$: {
						name: "Zimmer",
						udn: "uuid:871ab9db-6305-4cf6-8633-6d7405faadd5",
						powerState: "ACTIVE"
					},
					renderer: [{
						$: {
							udn: "uuid:e6d93437-8afd-46e0-8eb6-adebaf0f325c",
							name: "Speaker Zimmer",
							spotifyConnect: "active"
						}
					}]
				}]
			}]
		}
	}
}
```

I did this by disabling the Spotify multiroom mode as mentioned in https://github.com/ChriD/node-raumserver/issues/36#issuecomment-326746032

errors i get, are e.g.: 
```
{
requestUrl :  "/raumserver/controller/getRendererState?id=Zimmer&_=1516211865683",
action :  "getRendererState",
error :  true,
msg :  "Action was rejected",
data : {
errorMessage :  "Error: Media Renderer for id 'Zimmer' not found",
errorData :  null
}
}
```
or 
```
{
requestUrl :  "/raumserver/controller/pause?id=Zimmer&_=1516211865684",
action :  "pause",
error :  true,
msg :  "Action was rejected",
data : {
errorMessage :  "Error: VirtualMediaRenderer for id 'Zimmer' not found",
errorData :  null
}
}
```

Everything works fine on "Badezimmer" when Spotify is connected to "Zimmer". The opposite is the case when Spotify is connected to Badezimmer: the commands fail with the error above on Zimmer. So one can say the commands fail always on the active Spotify zone in "not multiroom mode".

**Comment by ChriD** [comment] 2018-01-17 19:12
Okay, thanks i will trake a look. I do not have spotify so it may be a bit hard to solve it

**Comment by gahujipo** [comment] 2018-01-17 19:52
Just write me an e-mail back. I give you some credentials for Spotify, so you can test it on your side right away.
